/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search clients and indexed documents within an authorized tenant */
        get: operations["search_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Local Console Context */
        get: operations["local_console_context_ui_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ui/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Local Console Logout */
        post: operations["local_console_logout_ui_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Clients Route */
        get: operations["list_clients_route_v1_clients_get"];
        put?: never;
        /** Create Client Route */
        post: operations["create_client_route_v1_clients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/clients/{client_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Client Route */
        get: operations["get_client_route_v1_clients__client_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Client Route */
        patch: operations["update_client_route_v1_clients__client_id__patch"];
        trace?: never;
    };
    "/v1/clients/{client_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Client Documents Route */
        get: operations["client_documents_route_v1_clients__client_id__documents_get"];
        put?: never;
        /** Ingest */
        post: operations["ingest_v1_clients__client_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/document-versions/{document_version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Document Status */
        get: operations["document_status_v1_document_versions__document_version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/document-versions/{document_version_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Document Version Content Route */
        get: operations["document_version_content_route_v1_document_versions__document_version_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document Route */
        get: operations["get_document_route_v1_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{document_id}/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Document Edit Route */
        get: operations["document_edit_route_v1_documents__document_id__edit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{document_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Document Revision Route */
        post: operations["document_revision_route_v1_documents__document_id__revisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/documents/{document_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Document Versions Route */
        get: operations["document_versions_route_v1_documents__document_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ClientDocumentPageResponse */
        ClientDocumentPageResponse: {
            /** Documents */
            documents: components["schemas"]["ClientDocumentTimelineItemResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** ClientDocumentTimelineItemResponse */
        ClientDocumentTimelineItemResponse: {
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /** Created At */
            created_at: string;
            /**
             * Current Document Version Id
             * Format: uuid
             */
            current_document_version_id: string;
            /** Current Version Number */
            current_version_number: number;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Indexing Status */
            indexing_status: string;
            /** Summary */
            summary: string | null;
            summary_status: components["schemas"]["SummaryStatus"];
            /** Title */
            title: string;
        };
        /** ClientPageResponse */
        ClientPageResponse: {
            /** Clients */
            clients: components["schemas"]["ClientResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** ClientResponse */
        ClientResponse: {
            /** Created At */
            created_at: string;
            /**
             * Creation Authorization Decision Id
             * Format: uuid
             */
            creation_authorization_decision_id: string;
            /** Description */
            description: string | null;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Name */
            last_name: string;
            /** Retrieval Authorization Decision Id */
            retrieval_authorization_decision_id: string | null;
            /** Social Links */
            social_links: string[];
            /** Source Reference */
            source_reference: string;
            /** Source Type */
            source_type: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Updated At */
            updated_at: string;
        };
        /** ClientSearchProvenanceResponse */
        ClientSearchProvenanceResponse: {
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /**
             * Creation Authorization Decision Id
             * Format: uuid
             */
            creation_authorization_decision_id: string;
            /**
             * Search Authorization Decision Id
             * Format: uuid
             */
            search_authorization_decision_id: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
        };
        /** ClientSearchResultResponse */
        ClientSearchResultResponse: {
            /** Email */
            email: string;
            /** Excerpt */
            excerpt: string | null;
            /** Fused Score */
            fused_score: number;
            /** Match Band */
            match_band: number;
            provenance: components["schemas"]["ClientSearchProvenanceResponse"];
            ranks: components["schemas"]["SearchRanksResponse"];
            /** Title */
            title: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "client";
        };
        /** ConsoleContextResponse */
        ConsoleContextResponse: {
            /** Advisor */
            advisor: string;
            workspace: components["schemas"]["WorkspaceSummaryResponse"];
        };
        /** CreateClientRequest */
        CreateClientRequest: {
            /** Description */
            description?: string | null;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Social Links */
            social_links?: string[];
            /** Source Reference */
            source_reference: string;
            /** Source Type */
            source_type: string;
        };
        /** CreateClientResponse */
        CreateClientResponse: {
            /** Created At */
            created_at: string;
            /**
             * Creation Authorization Decision Id
             * Format: uuid
             */
            creation_authorization_decision_id: string;
            /** Description */
            description: string | null;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Name */
            last_name: string;
            /** Outcome */
            outcome: string;
            /** Retrieval Authorization Decision Id */
            retrieval_authorization_decision_id: string | null;
            /** Social Links */
            social_links: string[];
            /** Source Reference */
            source_reference: string;
            /** Source Type */
            source_type: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Updated At */
            updated_at: string;
        };
        /** DocumentEditResponse */
        DocumentEditResponse: {
            /** Client Id */
            client_id: string | null;
            /** Content */
            content: string;
            /**
             * Current Document Version Id
             * Format: uuid
             */
            current_document_version_id: string;
            /** Current Version Number */
            current_version_number: number;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Title */
            title: string;
        };
        /** DocumentResourceResponse */
        DocumentResourceResponse: {
            /** Client Id */
            client_id: string | null;
            /** Created At */
            created_at: string;
            /**
             * Current Document Version Id
             * Format: uuid
             */
            current_document_version_id: string;
            /** Current Version Number */
            current_version_number: number;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** External Document Id */
            external_document_id: string;
            /** Indexing Status */
            indexing_status: string;
            /**
             * Ingestion Authorization Decision Id
             * Format: uuid
             */
            ingestion_authorization_decision_id: string;
            /**
             * Retrieval Authorization Decision Id
             * Format: uuid
             */
            retrieval_authorization_decision_id: string;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /** Source Reference */
            source_reference: string;
            /** Summary */
            summary: string | null;
            summary_status: components["schemas"]["SummaryStatus"];
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
            /** Title */
            title: string;
        };
        /** DocumentRevisionRequest */
        DocumentRevisionRequest: {
            /** Content */
            content: string;
            /** Title */
            title: string;
        };
        /** DocumentVersionContentResponse */
        DocumentVersionContentResponse: {
            /** Content */
            content: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Document Version Id
             * Format: uuid
             */
            document_version_id: string;
            /** Version Number */
            version_number: number;
        };
        /** DocumentVersionStatusResponse */
        DocumentVersionStatusResponse: {
            /** Chunk Count */
            chunk_count: number;
            /** Completed At */
            completed_at: string | null;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Document Version Id
             * Format: uuid
             */
            document_version_id: string;
            /** Failed At */
            failed_at: string | null;
            /** Failure Code */
            failure_code: string | null;
            /** Indexing Status */
            indexing_status: string;
            /** Queued At */
            queued_at: string | null;
            /** Version Number */
            version_number: number;
        };
        /** DocumentVersionTimelineItemResponse */
        DocumentVersionTimelineItemResponse: {
            /** Created At */
            created_at: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Document Version Id
             * Format: uuid
             */
            document_version_id: string;
            /** Indexing Status */
            indexing_status: string;
            /** Version Number */
            version_number: number;
        };
        /** DocumentVersionTimelineResponse */
        DocumentVersionTimelineResponse: {
            /** Versions */
            versions: components["schemas"]["DocumentVersionTimelineItemResponse"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestDocumentRequest */
        IngestDocumentRequest: {
            /** Content */
            content: string;
            /** External Document Id */
            external_document_id: string;
            /** Source Reference */
            source_reference: string;
            /** Title */
            title: string;
        };
        /** IngestDocumentResponse */
        IngestDocumentResponse: {
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Document Version Id
             * Format: uuid
             */
            document_version_id: string;
            /** Indexing Status */
            indexing_status: string;
            /** Outcome */
            outcome: string;
            /** Version Number */
            version_number: number;
        };
        /** SearchProvenanceResponse */
        SearchProvenanceResponse: {
            /**
             * Client Id
             * Format: uuid
             */
            client_id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Document Version Id
             * Format: uuid
             */
            document_version_id: string;
            /**
             * Embedding Profile Id
             * Format: uuid
             */
            embedding_profile_id: string;
            /**
             * Indexing Authorization Decision Id
             * Format: uuid
             */
            indexing_authorization_decision_id: string;
            /**
             * Search Authorization Decision Id
             * Format: uuid
             */
            search_authorization_decision_id: string;
            /**
             * Source Id
             * Format: uuid
             */
            source_id: string;
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
        };
        /** SearchRanksResponse */
        SearchRanksResponse: {
            /** Client Lexical */
            client_lexical: number | null;
            /** Document Lexical */
            document_lexical: number | null;
            /** Document Reranker */
            document_reranker: number | null;
            /** Document Semantic */
            document_semantic: number | null;
        };
        /** SearchResponse */
        SearchResponse: {
            /** Mode */
            mode: string;
            /** Next Cursor */
            next_cursor: string | null;
            /** Ranking Version */
            ranking_version: string;
            /** Results */
            results: (components["schemas"]["ClientSearchResultResponse"] | components["schemas"]["SearchResultResponse"])[];
        };
        /** SearchResultResponse */
        SearchResultResponse: {
            /** Client Name */
            client_name: string;
            /** Fused Score */
            fused_score: number;
            /** Match Band */
            match_band: number;
            provenance: components["schemas"]["SearchProvenanceResponse"];
            ranks: components["schemas"]["SearchRanksResponse"];
            scores: components["schemas"]["SearchScoresResponse"];
            /** Snippet */
            snippet: string;
            /** Title */
            title: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "document";
        };
        /** SearchScoresResponse */
        SearchScoresResponse: {
            /** Lexical */
            lexical: number | null;
            /** Reranker */
            reranker: number | null;
            /** Semantic */
            semantic: number | null;
        };
        /**
         * SummaryStatus
         * @enum {string}
         */
        SummaryStatus: "not_requested" | "pending" | "processing" | "ready" | "failed";
        /** UpdateClientRequest */
        UpdateClientRequest: {
            /** Description */
            description?: string | null;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Social Links */
            social_links?: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkspaceSummaryResponse */
        WorkspaceSummaryResponse: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    search_search_get: {
        parameters: {
            query: {
                q: string;
                limit?: number | null;
                cursor?: string | null;
            };
            header?: {
                "x-request-id"?: string | null;
                "x-nevis-tenant"?: string | null;
                "x-nevis-advisor"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    local_console_context_ui_context_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsoleContextResponse"];
                };
            };
        };
    };
    local_console_logout_ui_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_clients_route_v1_clients_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                "x-request-id"?: string | null;
                "x-nevis-tenant"?: string | null;
                "x-nevis-advisor"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_client_route_v1_clients_post: {
        parameters: {
            query?: never;
            header: {
                "idempotency-key": string;
                "x-request-id"?: string | null;
                "x-nevis-tenant"?: string | null;
                "x-nevis-advisor"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClientRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateClientResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_client_route_v1_clients__client_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-request-id"?: string | null;
                "x-nevis-tenant"?: string | null;
                "x-nevis-advisor"?: string | null;
            };
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_client_route_v1_clients__client_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-request-id"?: string | null;
                "x-nevis-tenant"?: string | null;
                "x-nevis-advisor"?: string | null;
            };
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateClientRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    client_documents_route_v1_clients__client_id__documents_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                "x-request-id"?: string | null;
                "x-nevis-tenant"?: string | null;
                "x-nevis-advisor"?: string | null;
            };
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientDocumentPageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_v1_clients__client_id__documents_post: {
        parameters: {
            query?: never;
            header: {
                "idempotency-key": string;
                "x-request-id"?: string | null;
                "x-nevis-tenant"?: string | null;
                "x-nevis-advisor"?: string | null;
            };
            path: {
                client_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestDocumentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    document_status_v1_document_versions__document_version_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-request-id"?: string | null;
                "x-nevis-tenant"?: string | null;
                "x-nevis-advisor"?: string | null;
            };
            path: {
                document_version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentVersionStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    document_version_content_route_v1_document_versions__document_version_id__content_get: {
        parameters: {
            query?: never;
            header?: {
                "x-request-id"?: string | null;
                "x-nevis-tenant"?: string | null;
                "x-nevis-advisor"?: string | null;
            };
            path: {
                document_version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentVersionContentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_route_v1_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-request-id"?: string | null;
                "x-nevis-tenant"?: string | null;
                "x-nevis-advisor"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    document_edit_route_v1_documents__document_id__edit_get: {
        parameters: {
            query?: never;
            header?: {
                "x-request-id"?: string | null;
                "x-nevis-tenant"?: string | null;
                "x-nevis-advisor"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentEditResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    document_revision_route_v1_documents__document_id__revisions_post: {
        parameters: {
            query?: never;
            header: {
                "idempotency-key": string;
                "x-request-id"?: string | null;
                "x-nevis-tenant"?: string | null;
                "x-nevis-advisor"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentRevisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestDocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    document_versions_route_v1_documents__document_id__versions_get: {
        parameters: {
            query?: never;
            header?: {
                "x-request-id"?: string | null;
                "x-nevis-tenant"?: string | null;
                "x-nevis-advisor"?: string | null;
            };
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentVersionTimelineResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
